# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Offline_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ofline_Viewer(object):
    def setupUi(self, Ofline_Viewer):
        Ofline_Viewer.setObjectName("Ofline_Viewer")
        Ofline_Viewer.resize(1067, 751)
        self.centralwidget = QtWidgets.QWidget(Ofline_Viewer)
        self.centralwidget.setObjectName("centralwidget")
        self.X_Pos_Plot_offline = QtWidgets.QPushButton(self.centralwidget)
        self.X_Pos_Plot_offline.setGeometry(QtCore.QRect(60, 210, 241, 41))
        self.X_Pos_Plot_offline.setObjectName("X_Pos_Plot_offline")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(60, 120, 91, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.std_LA_text_offline = QtWidgets.QLineEdit(self.centralwidget)
        self.std_LA_text_offline.setGeometry(QtCore.QRect(150, 120, 161, 21))
        self.std_LA_text_offline.setObjectName("std_LA_text_offline")
        self.std_SA_text_offline = QtWidgets.QLineEdit(self.centralwidget)
        self.std_SA_text_offline.setGeometry(QtCore.QRect(150, 150, 161, 21))
        self.std_SA_text_offline.setObjectName("std_SA_text_offline")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(60, 60, 91, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(60, 150, 91, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.Y_Pos_Plot_offline = QtWidgets.QPushButton(self.centralwidget)
        self.Y_Pos_Plot_offline.setGeometry(QtCore.QRect(60, 260, 241, 41))
        self.Y_Pos_Plot_offline.setObjectName("Y_Pos_Plot_offline")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 90, 91, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.Circularity = QtWidgets.QLineEdit(self.centralwidget)
        self.Circularity.setEnabled(False)
        self.Circularity.setGeometry(QtCore.QRect(60, 180, 91, 21))
        self.Circularity.setObjectName("Circularity")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(110, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.y_position_text_offline = QtWidgets.QLineEdit(self.centralwidget)
        self.y_position_text_offline.setGeometry(QtCore.QRect(150, 90, 161, 21))
        self.y_position_text_offline.setObjectName("y_position_text_offline")
        self.circularity_text_offline = QtWidgets.QLineEdit(self.centralwidget)
        self.circularity_text_offline.setGeometry(QtCore.QRect(150, 180, 161, 21))
        self.circularity_text_offline.setObjectName("circularity_text_offline")
        self.x_position_text_offline = QtWidgets.QLineEdit(self.centralwidget)
        self.x_position_text_offline.setGeometry(QtCore.QRect(150, 60, 161, 21))
        self.x_position_text_offline.setObjectName("x_position_text_offline")
        self.Frame_view = QtWidgets.QLabel(self.centralwidget)
        self.Frame_view.setGeometry(QtCore.QRect(330, 60, 721, 521))
        self.Frame_view.setText("")
        self.Frame_view.setScaledContents(False)
        self.Frame_view.setAlignment(QtCore.Qt.AlignCenter)
        self.Frame_view.setObjectName("Frame_view")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(650, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.FrameSlider = QtWidgets.QSlider(self.centralwidget)
        self.FrameSlider.setGeometry(QtCore.QRect(450, 620, 491, 20))
        self.FrameSlider.setMinimum(0)
        self.FrameSlider.setMaximum(1000)
        self.FrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.FrameSlider.setObjectName("FrameSlider")
        self.FrameNr = QtWidgets.QLineEdit(self.centralwidget)
        self.FrameNr.setGeometry(QtCore.QRect(620, 640, 113, 21))
        self.FrameNr.setObjectName("FrameNr")
        Ofline_Viewer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Ofline_Viewer)
        self.statusbar.setObjectName("statusbar")
        Ofline_Viewer.setStatusBar(self.statusbar)

        self.retranslateUi(Ofline_Viewer)
        QtCore.QMetaObject.connectSlotsByName(Ofline_Viewer)

    def retranslateUi(self, Ofline_Viewer):
        _translate = QtCore.QCoreApplication.translate
        Ofline_Viewer.setWindowTitle(_translate("Ofline_Viewer", "Offline View"))
        self.X_Pos_Plot_offline.setText(_translate("Ofline_Viewer", "Plot X-Position along time"))
        self.lineEdit_7.setText(_translate("Ofline_Viewer", "Std Long axis"))
        self.lineEdit_5.setText(_translate("Ofline_Viewer", "X-Position"))
        self.lineEdit_8.setText(_translate("Ofline_Viewer", "Std Short axis"))
        self.Y_Pos_Plot_offline.setText(_translate("Ofline_Viewer", "Plot Y-Position along time"))
        self.lineEdit_6.setText(_translate("Ofline_Viewer", "Y-Position"))
        self.Circularity.setText(_translate("Ofline_Viewer", "Circularity"))
        self.lineEdit.setText(_translate("Ofline_Viewer", "Resultes"))
        self.lineEdit_2.setText(_translate("Ofline_Viewer", "Frame View"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ofline_Viewer = QtWidgets.QMainWindow()
    ui = Ui_Ofline_Viewer()
    ui.setupUi(Ofline_Viewer)
    Ofline_Viewer.show()
    sys.exit(app.exec_())
